# Generated by Django 3.0.4 on 2020-03-29 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisv1', '0002_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 8, 10, 55, 775237)),
        ),
    ]
