# Generated by Django 3.0.4 on 2020-03-29 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisv1', '0003_accesstoken_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 8, 49, 49, 320610)),
        ),
    ]
