# Generated by Django 3.0.4 on 2020-03-29 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisv1', '0004_auto_20200329_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 9, 34, 10, 195789)),
        ),
    ]
