# Generated by Django 3.0 on 2020-03-29 16:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apisv1', '0005_auto_20200329_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='item_list',
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 16, 17, 51, 371602)),
        ),
        migrations.CreateModel(
            name='ItemOrderMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisv1.Items')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apisv1.UserOrder')),
            ],
        ),
    ]
