# Generated by Django 3.0 on 2020-03-30 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisv1', '0006_auto_20200329_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='order_item_status',
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 11, 24, 0, 79726)),
        ),
    ]
