# Generated by Django 3.0 on 2020-04-05 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisv1', '0007_auto_20200330_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 14, 40, 40, 838608)),
        ),
    ]
