# Generated by Django 3.0 on 2020-04-12 08:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apisv1', '0009_auto_20200409_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 8, 49, 2, 688995)),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
