# Generated by Django 3.0 on 2020-04-12 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apisv1', '0011_auto_20200412_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerorder',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 10, 8, 27, 251894)),
        ),
    ]
